### ISSUE TITLE
Problem with the Owl-carousel

### ISSUE THREAD

**Issue by amfaymos** [ruksah/Burger#1]
To fix this, try removing [.owl-stage-outer .owl-stage] & [.owl-item] from the style.css file

![Capture](https://user-images.githubusercontent.com/80521215/122165034-3c9a3c80-ce3d-11eb-88ac-2b6bc5af7a30.PNG)

**Comment by ruksah** [comment]
Thank you for your reply.
Inn Sha Allah I will try and let u know.
